### ISSUE TITLE
Circular dependency between testee and grunt-testee

### ISSUE THREAD

**Issue by pmgmendes** [bitovi/grunt-testee#3]
After the update to testee@^0.6.1 I'm getting the a warning in `npm install`
`npm WARN grunt-testee@1.0.0 requires a peer of grunt@>=0.4.0 but none was installed.`
npm-shrinkwrap.json fails to generate thronwing the error
`npm ERR! peer invalid: grunt@>=0.4.0, required by grunt-testee@1.0.0`
Inspecting [testee](https://github.com/bitovi/testee/blob/v0.6.1/package.json#L27) and [grunt-testee](https://github.com/bitovi/grunt-testee/blob/v1.0.0/package.json#L14) dependencies I've detected the circular dependency.
I'm not sure this is causing the warning/error but it shouldn't be set up like this, right?

**Comment by andrejewski** [comment]
This is expected and intended; it will be removed in Testee v0.7. However, I was unaware that shrinkwrap would choke on this. I can escalate an minor release of 0.7 if this is important. Out of curiosity, how does a package-lock handle in this scenario? I haven't had an issue with it.

**Comment by pmgmendes** [comment]
Hi @andrejewski,
Sorry the late reply. Yes, the error is not related to that. The issue is on `npm ERR! peer invalid: grunt@>=0.4.0, required by grunt-testee@1.0.0` error.
But I not sure what do I need to change to overcome this.
I guess the this issue can be closed.

**Comment by andrejewski** [comment]
You can try installing `grunt` and adding it to your package.json, then the peer dependency would be satisfied. I don't like having to force you to do that though. I'll try to get a new Testee release out soon to address this for you.

**Comment by andrejewski** [comment]
I released [v0.7](https://github.com/bitovi/testee/releases/tag/v0.7.0) which fixes this vicious dependency cycle.
